
# This file is automatically generated, you probably don't want to edit this

obtcasecontrolOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "obtcasecontrolOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            exposureVar = NULL,
            exposedLevel = "1",
            outcomeVar = NULL,
            caseLevel = "1",
            ciLevel = 0.95,
            showForest = TRUE, ...) {

            super$initialize(
                package="outbreakTools",
                name="obtcasecontrol",
                requiresData=TRUE,
                ...)

            private$..exposureVar <- jmvcore::OptionVariable$new(
                "exposureVar",
                exposureVar,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor",
                    "id"))
            private$..exposedLevel <- jmvcore::OptionString$new(
                "exposedLevel",
                exposedLevel,
                default="1")
            private$..outcomeVar <- jmvcore::OptionVariable$new(
                "outcomeVar",
                outcomeVar,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor",
                    "id"))
            private$..caseLevel <- jmvcore::OptionString$new(
                "caseLevel",
                caseLevel,
                default="1")
            private$..ciLevel <- jmvcore::OptionNumber$new(
                "ciLevel",
                ciLevel,
                min=0.8,
                max=0.99,
                default=0.95)
            private$..showForest <- jmvcore::OptionBool$new(
                "showForest",
                showForest,
                default=TRUE)

            self$.addOption(private$..exposureVar)
            self$.addOption(private$..exposedLevel)
            self$.addOption(private$..outcomeVar)
            self$.addOption(private$..caseLevel)
            self$.addOption(private$..ciLevel)
            self$.addOption(private$..showForest)
        }),
    active = list(
        exposureVar = function() private$..exposureVar$value,
        exposedLevel = function() private$..exposedLevel$value,
        outcomeVar = function() private$..outcomeVar$value,
        caseLevel = function() private$..caseLevel$value,
        ciLevel = function() private$..ciLevel$value,
        showForest = function() private$..showForest$value),
    private = list(
        ..exposureVar = NA,
        ..exposedLevel = NA,
        ..outcomeVar = NA,
        ..caseLevel = NA,
        ..ciLevel = NA,
        ..showForest = NA)
)

obtcasecontrolResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "obtcasecontrolResults",
    inherit = jmvcore::Group,
    active = list(
        crossTab = function() private$.items[["crossTab"]],
        measuresTable = function() private$.items[["measuresTable"]],
        chiTable = function() private$.items[["chiTable"]],
        forestPlot = function() private$.items[["forestPlot"]],
        ccNote = function() private$.items[["ccNote"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Case-Control Study — Odds Ratio")
            self$add(jmvcore::Table$new(
                options=options,
                name="crossTab",
                title="2\u00D72 Contingency Table",
                columns=list(
                    list(
                        `name`="exposure", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="cases", 
                        `title`="Cases", 
                        `type`="integer"),
                    list(
                        `name`="controls", 
                        `title`="Controls", 
                        `type`="integer"),
                    list(
                        `name`="total", 
                        `title`="Total", 
                        `type`="integer"),
                    list(
                        `name`="exp_pct", 
                        `title`="Exposed %", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="measuresTable",
                title="Measures of Association",
                columns=list(
                    list(
                        `name`="measure", 
                        `title`="Measure", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="Estimate", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ci_low", 
                        `title`="CI Low", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ci_high", 
                        `title`="CI High", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="p_value", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="chiTable",
                title="Statistical Tests",
                columns=list(
                    list(
                        `name`="test", 
                        `title`="Test", 
                        `type`="text"),
                    list(
                        `name`="stat", 
                        `title`="Value", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="forestPlot",
                title="Estimate Plot",
                width=480,
                height=200,
                renderFun=".plotForest",
                visible="(showForest)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="ccNote",
                title="Interpretation & References",
                visible="always"))}))

obtcasecontrolBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "obtcasecontrolBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "outbreakTools",
                name = "obtcasecontrol",
                version = c(1,0,0),
                options = options,
                results = obtcasecontrolResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Case-Control Study — Odds Ratio
#'
#' 
#' @param data .
#' @param exposureVar .
#' @param exposedLevel .
#' @param outcomeVar .
#' @param caseLevel .
#' @param ciLevel .
#' @param showForest .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$crossTab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$measuresTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$chiTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$forestPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$ccNote} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$crossTab$asDF}
#'
#' \code{as.data.frame(results$crossTab)}
#'
#' @export
obtcasecontrol <- function(
    data,
    exposureVar,
    exposedLevel = "1",
    outcomeVar,
    caseLevel = "1",
    ciLevel = 0.95,
    showForest = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("obtcasecontrol requires jmvcore to be installed (restart may be required)")

    if ( ! missing(exposureVar)) exposureVar <- jmvcore::resolveQuo(jmvcore::enquo(exposureVar))
    if ( ! missing(outcomeVar)) outcomeVar <- jmvcore::resolveQuo(jmvcore::enquo(outcomeVar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(exposureVar), exposureVar, NULL),
            `if`( ! missing(outcomeVar), outcomeVar, NULL))


    options <- obtcasecontrolOptions$new(
        exposureVar = exposureVar,
        exposedLevel = exposedLevel,
        outcomeVar = outcomeVar,
        caseLevel = caseLevel,
        ciLevel = ciLevel,
        showForest = showForest)

    analysis <- obtcasecontrolClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

