
# This file is automatically generated, you probably don't want to edit this

obtcleanOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "obtcleanOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            idVar = NULL,
            dateVars = NULL,
            dateFormat = "auto",
            refStartDate = "",
            catVars = NULL,
            numVars = NULL,
            ageVar = NULL,
            ageMin = 0,
            ageMax = 110,
            missingThreshold = 20,
            showDuplicates = TRUE,
            showMissing = TRUE,
            showCatIssues = TRUE,
            showClustering = TRUE,
            clusterMethod = "fingerprint",
            showDateDiversity = TRUE,
            showRCode = TRUE, ...) {

            super$initialize(
                package="outbreakTools",
                name="obtclean",
                requiresData=TRUE,
                ...)

            private$..idVar <- jmvcore::OptionVariable$new(
                "idVar",
                idVar,
                suggested=list(
                    "id",
                    "nominal"),
                permitted=list(
                    "factor",
                    "id",
                    "numeric"),
                default=NULL)
            private$..dateVars <- jmvcore::OptionVariables$new(
                "dateVars",
                dateVars,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor",
                    "id"),
                default=NULL)
            private$..dateFormat <- jmvcore::OptionList$new(
                "dateFormat",
                dateFormat,
                options=list(
                    "auto",
                    "ymd",
                    "dmy",
                    "mdy"),
                default="auto")
            private$..refStartDate <- jmvcore::OptionString$new(
                "refStartDate",
                refStartDate,
                default="")
            private$..catVars <- jmvcore::OptionVariables$new(
                "catVars",
                catVars,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor",
                    "id"),
                default=NULL)
            private$..numVars <- jmvcore::OptionVariables$new(
                "numVars",
                numVars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..ageVar <- jmvcore::OptionVariable$new(
                "ageVar",
                ageVar,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..ageMin <- jmvcore::OptionInteger$new(
                "ageMin",
                ageMin,
                min=0,
                max=10,
                default=0)
            private$..ageMax <- jmvcore::OptionInteger$new(
                "ageMax",
                ageMax,
                min=50,
                max=130,
                default=110)
            private$..missingThreshold <- jmvcore::OptionNumber$new(
                "missingThreshold",
                missingThreshold,
                min=0,
                max=100,
                default=20)
            private$..showDuplicates <- jmvcore::OptionBool$new(
                "showDuplicates",
                showDuplicates,
                default=TRUE)
            private$..showMissing <- jmvcore::OptionBool$new(
                "showMissing",
                showMissing,
                default=TRUE)
            private$..showCatIssues <- jmvcore::OptionBool$new(
                "showCatIssues",
                showCatIssues,
                default=TRUE)
            private$..showClustering <- jmvcore::OptionBool$new(
                "showClustering",
                showClustering,
                default=TRUE)
            private$..clusterMethod <- jmvcore::OptionList$new(
                "clusterMethod",
                clusterMethod,
                options=list(
                    "fingerprint",
                    "ngram"),
                default="fingerprint")
            private$..showDateDiversity <- jmvcore::OptionBool$new(
                "showDateDiversity",
                showDateDiversity,
                default=TRUE)
            private$..showRCode <- jmvcore::OptionBool$new(
                "showRCode",
                showRCode,
                default=TRUE)

            self$.addOption(private$..idVar)
            self$.addOption(private$..dateVars)
            self$.addOption(private$..dateFormat)
            self$.addOption(private$..refStartDate)
            self$.addOption(private$..catVars)
            self$.addOption(private$..numVars)
            self$.addOption(private$..ageVar)
            self$.addOption(private$..ageMin)
            self$.addOption(private$..ageMax)
            self$.addOption(private$..missingThreshold)
            self$.addOption(private$..showDuplicates)
            self$.addOption(private$..showMissing)
            self$.addOption(private$..showCatIssues)
            self$.addOption(private$..showClustering)
            self$.addOption(private$..clusterMethod)
            self$.addOption(private$..showDateDiversity)
            self$.addOption(private$..showRCode)
        }),
    active = list(
        idVar = function() private$..idVar$value,
        dateVars = function() private$..dateVars$value,
        dateFormat = function() private$..dateFormat$value,
        refStartDate = function() private$..refStartDate$value,
        catVars = function() private$..catVars$value,
        numVars = function() private$..numVars$value,
        ageVar = function() private$..ageVar$value,
        ageMin = function() private$..ageMin$value,
        ageMax = function() private$..ageMax$value,
        missingThreshold = function() private$..missingThreshold$value,
        showDuplicates = function() private$..showDuplicates$value,
        showMissing = function() private$..showMissing$value,
        showCatIssues = function() private$..showCatIssues$value,
        showClustering = function() private$..showClustering$value,
        clusterMethod = function() private$..clusterMethod$value,
        showDateDiversity = function() private$..showDateDiversity$value,
        showRCode = function() private$..showRCode$value),
    private = list(
        ..idVar = NA,
        ..dateVars = NA,
        ..dateFormat = NA,
        ..refStartDate = NA,
        ..catVars = NA,
        ..numVars = NA,
        ..ageVar = NA,
        ..ageMin = NA,
        ..ageMax = NA,
        ..missingThreshold = NA,
        ..showDuplicates = NA,
        ..showMissing = NA,
        ..showCatIssues = NA,
        ..showClustering = NA,
        ..clusterMethod = NA,
        ..showDateDiversity = NA,
        ..showRCode = NA)
)

obtcleanResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "obtcleanResults",
    inherit = jmvcore::Group,
    active = list(
        overviewTable = function() private$.items[["overviewTable"]],
        missingTable = function() private$.items[["missingTable"]],
        duplicateTable = function() private$.items[["duplicateTable"]],
        dateTable = function() private$.items[["dateTable"]],
        numTable = function() private$.items[["numTable"]],
        catTable = function() private$.items[["catTable"]],
        clusterTable = function() private$.items[["clusterTable"]],
        dateFormatTable = function() private$.items[["dateFormatTable"]],
        rRecipes = function() private$.items[["rRecipes"]],
        cleaningReport = function() private$.items[["cleaningReport"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Data Quality & Linelist Check")
            self$add(jmvcore::Table$new(
                options=options,
                name="overviewTable",
                title="Dataset Overview",
                columns=list(
                    list(
                        `name`="metric", 
                        `title`="Metric", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="missingTable",
                title="Missing Data by Variable",
                visible="(showMissing)",
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="nMissing", 
                        `title`="N Missing", 
                        `type`="integer"),
                    list(
                        `name`="pctMissing", 
                        `title`="% Missing", 
                        `type`="number", 
                        `format`="zto,pct"),
                    list(
                        `name`="flag", 
                        `title`="Flag", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="duplicateTable",
                title="Duplicate Records",
                visible="(showDuplicates)",
                columns=list(
                    list(
                        `name`="id", 
                        `title`="ID Value", 
                        `type`="text"),
                    list(
                        `name`="count", 
                        `title`="N Duplicates", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="dateTable",
                title="Date Variable Audit",
                visible="(dateVars)",
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="issue", 
                        `title`="Issue Type", 
                        `type`="text"),
                    list(
                        `name`="nAffected", 
                        `title`="N Affected", 
                        `type`="integer"),
                    list(
                        `name`="examples", 
                        `title`="Examples", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="numTable",
                title="Numeric Variable Audit",
                visible="(numVars)",
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="min_val", 
                        `title`="Min", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="max_val", 
                        `title`="Max", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="mean_val", 
                        `title`="Mean", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="n_miss", 
                        `title`="N Missing", 
                        `type`="integer"),
                    list(
                        `name`="flag", 
                        `title`="Flag", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="catTable",
                title="Categorical Coding Audit",
                visible="(showCatIssues)",
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="level", 
                        `title`="Level", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="pct", 
                        `title`="%", 
                        `type`="number", 
                        `format`="zto,pct"),
                    list(
                        `name`="flag", 
                        `title`="Flag", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="clusterTable",
                title="Duplicate-Variant Clusters (OpenRefine-style)",
                visible="(showClustering)",
                columns=list(
                    list(
                        `name`="variable",
                        `title`="Variable",
                        `type`="text"),
                    list(
                        `name`="cluster_id",
                        `title`="Cluster #",
                        `type`="integer"),
                    list(
                        `name`="variant",
                        `title`="Variant value",
                        `type`="text"),
                    list(
                        `name`="n",
                        `title`="N occurrences",
                        `type`="integer"),
                    list(
                        `name`="suggestion",
                        `title`="Suggested canonical value",
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="dateFormatTable",
                title="Date Format Diversity",
                visible="(showDateDiversity)",
                columns=list(
                    list(
                        `name`="variable",
                        `title`="Variable",
                        `type`="text"),
                    list(
                        `name`="pattern",
                        `title`="Format pattern",
                        `type`="text"),
                    list(
                        `name`="n",
                        `title`="N records",
                        `type`="integer"),
                    list(
                        `name`="examples",
                        `title`="Examples",
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="rRecipes",
                title="R Cleaning Recipes (copy-paste)",
                visible="(showRCode)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="cleaningReport",
                title="Cleaning Report Summary",
                visible="always"))}))

obtcleanBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "obtcleanBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "outbreakTools",
                name = "obtclean",
                version = c(1,0,0),
                options = options,
                results = obtcleanResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Data Quality & Linelist Check
#'
#' Automated outbreak linelist quality audit. Detects duplicate records, 
#' missing data patterns, impossible/future dates, out-of-range numeric 
#' values, and inconsistent categorical coding. Generates a structured 
#' cleaning report for field documentation.
#' 
#' @param data .
#' @param idVar .
#' @param dateVars .
#' @param dateFormat .
#' @param refStartDate .
#' @param catVars .
#' @param numVars .
#' @param ageVar .
#' @param ageMin .
#' @param ageMax .
#' @param missingThreshold .
#' @param showDuplicates .
#' @param showMissing .
#' @param showCatIssues .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$overviewTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$missingTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$duplicateTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$dateTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$numTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$catTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$clusterTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$dateFormatTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$rRecipes} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$cleaningReport} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$overviewTable$asDF}
#'
#' \code{as.data.frame(results$overviewTable)}
#'
#' @export
obtclean <- function(
    data,
    idVar = NULL,
    dateVars = NULL,
    dateFormat = "auto",
    refStartDate = "",
    catVars = NULL,
    numVars = NULL,
    ageVar = NULL,
    ageMin = 0,
    ageMax = 110,
    missingThreshold = 20,
    showDuplicates = TRUE,
    showMissing = TRUE,
    showCatIssues = TRUE,
    showClustering = TRUE,
    clusterMethod = "fingerprint",
    showDateDiversity = TRUE,
    showRCode = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("obtclean requires jmvcore to be installed (restart may be required)")

    if ( ! missing(idVar)) idVar <- jmvcore::resolveQuo(jmvcore::enquo(idVar))
    if ( ! missing(dateVars)) dateVars <- jmvcore::resolveQuo(jmvcore::enquo(dateVars))
    if ( ! missing(catVars)) catVars <- jmvcore::resolveQuo(jmvcore::enquo(catVars))
    if ( ! missing(numVars)) numVars <- jmvcore::resolveQuo(jmvcore::enquo(numVars))
    if ( ! missing(ageVar)) ageVar <- jmvcore::resolveQuo(jmvcore::enquo(ageVar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(idVar), idVar, NULL),
            `if`( ! missing(dateVars), dateVars, NULL),
            `if`( ! missing(catVars), catVars, NULL),
            `if`( ! missing(numVars), numVars, NULL),
            `if`( ! missing(ageVar), ageVar, NULL))


    options <- obtcleanOptions$new(
        idVar = idVar,
        dateVars = dateVars,
        dateFormat = dateFormat,
        refStartDate = refStartDate,
        catVars = catVars,
        numVars = numVars,
        ageVar = ageVar,
        ageMin = ageMin,
        ageMax = ageMax,
        missingThreshold = missingThreshold,
        showDuplicates = showDuplicates,
        showMissing = showMissing,
        showCatIssues = showCatIssues,
        showClustering = showClustering,
        clusterMethod = clusterMethod,
        showDateDiversity = showDateDiversity,
        showRCode = showRCode)

    analysis <- obtcleanClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

