
# This file is automatically generated, you probably don't want to edit this

obtdescriptiveOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "obtdescriptiveOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            caseVar = NULL,
            caseLevel = "1",
            personVars = NULL,
            ageVar = NULL,
            showAR = TRUE,
            ciMethod = "wilson",
            ciLevel = 0.95,
            showMissing = TRUE, ...) {

            super$initialize(
                package="outbreakTools",
                name="obtdescriptive",
                requiresData=TRUE,
                ...)

            private$..caseVar <- jmvcore::OptionVariable$new(
                "caseVar",
                caseVar,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor",
                    "id"),
                default=NULL)
            private$..caseLevel <- jmvcore::OptionString$new(
                "caseLevel",
                caseLevel,
                default="1")
            private$..personVars <- jmvcore::OptionVariables$new(
                "personVars",
                personVars,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor",
                    "id",
                    "numeric"),
                default=NULL)
            private$..ageVar <- jmvcore::OptionVariable$new(
                "ageVar",
                ageVar,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..showAR <- jmvcore::OptionBool$new(
                "showAR",
                showAR,
                default=TRUE)
            private$..ciMethod <- jmvcore::OptionList$new(
                "ciMethod",
                ciMethod,
                options=list(
                    "wilson",
                    "exact",
                    "wald"),
                default="wilson")
            private$..ciLevel <- jmvcore::OptionNumber$new(
                "ciLevel",
                ciLevel,
                min=0.8,
                max=0.99,
                default=0.95)
            private$..showMissing <- jmvcore::OptionBool$new(
                "showMissing",
                showMissing,
                default=TRUE)

            self$.addOption(private$..caseVar)
            self$.addOption(private$..caseLevel)
            self$.addOption(private$..personVars)
            self$.addOption(private$..ageVar)
            self$.addOption(private$..showAR)
            self$.addOption(private$..ciMethod)
            self$.addOption(private$..ciLevel)
            self$.addOption(private$..showMissing)
        }),
    active = list(
        caseVar = function() private$..caseVar$value,
        caseLevel = function() private$..caseLevel$value,
        personVars = function() private$..personVars$value,
        ageVar = function() private$..ageVar$value,
        showAR = function() private$..showAR$value,
        ciMethod = function() private$..ciMethod$value,
        ciLevel = function() private$..ciLevel$value,
        showMissing = function() private$..showMissing$value),
    private = list(
        ..caseVar = NA,
        ..caseLevel = NA,
        ..personVars = NA,
        ..ageVar = NA,
        ..showAR = NA,
        ..ciMethod = NA,
        ..ciLevel = NA,
        ..showMissing = NA)
)

obtdescriptiveResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "obtdescriptiveResults",
    inherit = jmvcore::Group,
    active = list(
        ageTable = function() private$.items[["ageTable"]],
        freqTables = function() private$.items[["freqTables"]],
        descNote = function() private$.items[["descNote"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Descriptive Epidemiology")
            self$add(jmvcore::Table$new(
                options=options,
                name="ageTable",
                title="Age Summary (Cases)",
                visible="(ageVar)",
                columns=list(
                    list(
                        `name`="stat", 
                        `title`="Statistic", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Array$new(
                options=options,
                name="freqTables",
                title="Frequency Tables",
                items="(personVars)",
                template=jmvcore::Table$new(
                    options=options,
                    title="$key",
                    columns=list(
                        list(
                            `name`="level", 
                            `title`="Category", 
                            `type`="text"),
                        list(
                            `name`="n", 
                            `title`="N Cases", 
                            `type`="integer"),
                        list(
                            `name`="total", 
                            `title`="N Total", 
                            `type`="integer"),
                        list(
                            `name`="pct", 
                            `title`="% (of cases)", 
                            `type`="number", 
                            `format`="zto,pct"),
                        list(
                            `name`="ar", 
                            `title`="Attack Rate", 
                            `type`="number", 
                            `format`="zto,pct"),
                        list(
                            `name`="ci_low", 
                            `title`="CI Low", 
                            `type`="number", 
                            `format`="zto,pct"),
                        list(
                            `name`="ci_high", 
                            `title`="CI High", 
                            `type`="number", 
                            `format`="zto,pct")))))
            self$add(jmvcore::Html$new(
                options=options,
                name="descNote",
                title="Notes & References",
                visible="always"))}))

obtdescriptiveBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "obtdescriptiveBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "outbreakTools",
                name = "obtdescriptive",
                version = c(1,0,0),
                options = options,
                results = obtdescriptiveResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Descriptive Epidemiology
#'
#' 
#' @param data .
#' @param caseVar .
#' @param caseLevel .
#' @param personVars .
#' @param ageVar .
#' @param showAR .
#' @param ciMethod .
#' @param ciLevel .
#' @param showMissing .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$ageTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$freqTables} \tab \tab \tab \tab \tab an array of tables \cr
#'   \code{results$descNote} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$ageTable$asDF}
#'
#' \code{as.data.frame(results$ageTable)}
#'
#' @export
obtdescriptive <- function(
    data,
    caseVar = NULL,
    caseLevel = "1",
    personVars = NULL,
    ageVar = NULL,
    showAR = TRUE,
    ciMethod = "wilson",
    ciLevel = 0.95,
    showMissing = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("obtdescriptive requires jmvcore to be installed (restart may be required)")

    if ( ! missing(caseVar)) caseVar <- jmvcore::resolveQuo(jmvcore::enquo(caseVar))
    if ( ! missing(personVars)) personVars <- jmvcore::resolveQuo(jmvcore::enquo(personVars))
    if ( ! missing(ageVar)) ageVar <- jmvcore::resolveQuo(jmvcore::enquo(ageVar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(caseVar), caseVar, NULL),
            `if`( ! missing(personVars), personVars, NULL),
            `if`( ! missing(ageVar), ageVar, NULL))


    options <- obtdescriptiveOptions$new(
        caseVar = caseVar,
        caseLevel = caseLevel,
        personVars = personVars,
        ageVar = ageVar,
        showAR = showAR,
        ciMethod = ciMethod,
        ciLevel = ciLevel,
        showMissing = showMissing)

    analysis <- obtdescriptiveClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

