
# This file is automatically generated, you probably don't want to edit this

obtepicurveOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "obtepicurveOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dateVar = NULL,
            groupVar = NULL,
            timeUnit = "week",
            dateFormat = "auto",
            plotTitle = "Epidemic Curve",
            xLabel = "Date / Period of Symptom Onset",
            yLabel = "Number of Cases",
            fillColour = "navy",
            showTable = TRUE,
            showNLabel = TRUE,
            showPeakLine = TRUE, ...) {

            super$initialize(
                package="outbreakTools",
                name="obtepicurve",
                requiresData=TRUE,
                ...)

            private$..dateVar <- jmvcore::OptionVariable$new(
                "dateVar",
                dateVar,
                suggested=list(
                    "continuous",
                    "ordinal",
                    "nominal"),
                permitted=list(
                    "numeric",
                    "factor",
                    "id"))
            private$..groupVar <- jmvcore::OptionVariable$new(
                "groupVar",
                groupVar,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor",
                    "id"),
                default=NULL)
            private$..timeUnit <- jmvcore::OptionList$new(
                "timeUnit",
                timeUnit,
                options=list(
                    "day",
                    "week",
                    "week_sun",
                    "month"),
                default="week")
            private$..dateFormat <- jmvcore::OptionList$new(
                "dateFormat",
                dateFormat,
                options=list(
                    "auto",
                    "ymd",
                    "dmy",
                    "mdy"),
                default="auto")
            private$..plotTitle <- jmvcore::OptionString$new(
                "plotTitle",
                plotTitle,
                default="Epidemic Curve")
            private$..xLabel <- jmvcore::OptionString$new(
                "xLabel",
                xLabel,
                default="Date / Period of Symptom Onset")
            private$..yLabel <- jmvcore::OptionString$new(
                "yLabel",
                yLabel,
                default="Number of Cases")
            private$..fillColour <- jmvcore::OptionList$new(
                "fillColour",
                fillColour,
                options=list(
                    "navy",
                    "red",
                    "green",
                    "steel",
                    "orange"),
                default="navy")
            private$..showTable <- jmvcore::OptionBool$new(
                "showTable",
                showTable,
                default=TRUE)
            private$..showNLabel <- jmvcore::OptionBool$new(
                "showNLabel",
                showNLabel,
                default=TRUE)
            private$..showPeakLine <- jmvcore::OptionBool$new(
                "showPeakLine",
                showPeakLine,
                default=TRUE)

            self$.addOption(private$..dateVar)
            self$.addOption(private$..groupVar)
            self$.addOption(private$..timeUnit)
            self$.addOption(private$..dateFormat)
            self$.addOption(private$..plotTitle)
            self$.addOption(private$..xLabel)
            self$.addOption(private$..yLabel)
            self$.addOption(private$..fillColour)
            self$.addOption(private$..showTable)
            self$.addOption(private$..showNLabel)
            self$.addOption(private$..showPeakLine)
        }),
    active = list(
        dateVar = function() private$..dateVar$value,
        groupVar = function() private$..groupVar$value,
        timeUnit = function() private$..timeUnit$value,
        dateFormat = function() private$..dateFormat$value,
        plotTitle = function() private$..plotTitle$value,
        xLabel = function() private$..xLabel$value,
        yLabel = function() private$..yLabel$value,
        fillColour = function() private$..fillColour$value,
        showTable = function() private$..showTable$value,
        showNLabel = function() private$..showNLabel$value,
        showPeakLine = function() private$..showPeakLine$value),
    private = list(
        ..dateVar = NA,
        ..groupVar = NA,
        ..timeUnit = NA,
        ..dateFormat = NA,
        ..plotTitle = NA,
        ..xLabel = NA,
        ..yLabel = NA,
        ..fillColour = NA,
        ..showTable = NA,
        ..showNLabel = NA,
        ..showPeakLine = NA)
)

obtepicurveResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "obtepicurveResults",
    inherit = jmvcore::Group,
    active = list(
        epicurvePlot = function() private$.items[["epicurvePlot"]],
        caseTable = function() private$.items[["caseTable"]],
        epicurveSummary = function() private$.items[["epicurveSummary"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Epidemic Curve")
            self$add(jmvcore::Image$new(
                options=options,
                name="epicurvePlot",
                title="Epidemic Curve",
                width=720,
                height=460,
                renderFun=".plot",
                requiresData=TRUE,
                clearWith=list(
                    "dateVar",
                    "groupVar",
                    "timeUnit",
                    "dateFormat",
                    "plotTitle",
                    "xLabel",
                    "yLabel",
                    "fillColour",
                    "showNLabel",
                    "showPeakLine")))
            self$add(jmvcore::Table$new(
                options=options,
                name="caseTable",
                title="Case Counts by Period",
                visible="(showTable)",
                clearWith=list(
                    "dateVar",
                    "groupVar",
                    "timeUnit",
                    "dateFormat"),
                columns=list(
                    list(
                        `name`="period", 
                        `title`="Period", 
                        `type`="text"),
                    list(
                        `name`="epiWk", 
                        `title`="Epi Week", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="N Cases", 
                        `type`="integer"),
                    list(
                        `name`="pct", 
                        `title`="%", 
                        `type`="number", 
                        `format`="zto,pct"),
                    list(
                        `name`="cumN", 
                        `title`="Cumulative N", 
                        `type`="integer"),
                    list(
                        `name`="cumPct", 
                        `title`="Cumulative %", 
                        `type`="number", 
                        `format`="zto,pct"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="epicurveSummary",
                title="Summary Statistics",
                visible="always"))}))

obtepicurveBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "obtepicurveBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "outbreakTools",
                name = "obtepicurve",
                version = c(1,0,0),
                options = options,
                results = obtepicurveResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Epidemic Curve
#'
#' Generates publication-quality epidemic curves (histograms of case counts 
#' over time) for outbreak investigation. Supports ISO epi-week, day, and 
#' month intervals. Includes optional case classification grouping and 
#' case-count table.
#' 
#' @param data .
#' @param dateVar .
#' @param groupVar .
#' @param timeUnit .
#' @param dateFormat .
#' @param plotTitle .
#' @param xLabel .
#' @param yLabel .
#' @param fillColour .
#' @param showTable .
#' @param showNLabel .
#' @param showPeakLine .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$epicurvePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$caseTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$epicurveSummary} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$caseTable$asDF}
#'
#' \code{as.data.frame(results$caseTable)}
#'
#' @export
obtepicurve <- function(
    data,
    dateVar,
    groupVar = NULL,
    timeUnit = "week",
    dateFormat = "auto",
    plotTitle = "Epidemic Curve",
    xLabel = "Date / Period of Symptom Onset",
    yLabel = "Number of Cases",
    fillColour = "navy",
    showTable = TRUE,
    showNLabel = TRUE,
    showPeakLine = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("obtepicurve requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dateVar)) dateVar <- jmvcore::resolveQuo(jmvcore::enquo(dateVar))
    if ( ! missing(groupVar)) groupVar <- jmvcore::resolveQuo(jmvcore::enquo(groupVar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dateVar), dateVar, NULL),
            `if`( ! missing(groupVar), groupVar, NULL))


    options <- obtepicurveOptions$new(
        dateVar = dateVar,
        groupVar = groupVar,
        timeUnit = timeUnit,
        dateFormat = dateFormat,
        plotTitle = plotTitle,
        xLabel = xLabel,
        yLabel = yLabel,
        fillColour = fillColour,
        showTable = showTable,
        showNLabel = showNLabel,
        showPeakLine = showPeakLine)

    analysis <- obtepicurveClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

