
# This file is automatically generated, you probably don't want to edit this

obtlogisticOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "obtlogisticOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            outcomeVar = NULL,
            caseLevel = "1",
            exposures = NULL,
            autoScreen = TRUE,
            ciLevel = 0.95,
            showForest = TRUE,
            showFit = TRUE, ...) {

            super$initialize(
                package="outbreakTools",
                name="obtlogistic",
                requiresData=TRUE,
                ...)

            private$..outcomeVar <- jmvcore::OptionVariable$new(
                "outcomeVar",
                outcomeVar,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor",
                    "id"))
            private$..caseLevel <- jmvcore::OptionString$new(
                "caseLevel",
                caseLevel,
                default="1")
            private$..exposures <- jmvcore::OptionVariables$new(
                "exposures",
                exposures,
                suggested=list(
                    "nominal",
                    "ordinal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "id",
                    "numeric"))
            private$..autoScreen <- jmvcore::OptionBool$new(
                "autoScreen",
                autoScreen,
                default=TRUE)
            private$..ciLevel <- jmvcore::OptionNumber$new(
                "ciLevel",
                ciLevel,
                min=0.8,
                max=0.99,
                default=0.95)
            private$..showForest <- jmvcore::OptionBool$new(
                "showForest",
                showForest,
                default=TRUE)
            private$..showFit <- jmvcore::OptionBool$new(
                "showFit",
                showFit,
                default=TRUE)

            self$.addOption(private$..outcomeVar)
            self$.addOption(private$..caseLevel)
            self$.addOption(private$..exposures)
            self$.addOption(private$..autoScreen)
            self$.addOption(private$..ciLevel)
            self$.addOption(private$..showForest)
            self$.addOption(private$..showFit)
        }),
    active = list(
        outcomeVar = function() private$..outcomeVar$value,
        caseLevel = function() private$..caseLevel$value,
        exposures = function() private$..exposures$value,
        autoScreen = function() private$..autoScreen$value,
        ciLevel = function() private$..ciLevel$value,
        showForest = function() private$..showForest$value,
        showFit = function() private$..showFit$value),
    private = list(
        ..outcomeVar = NA,
        ..caseLevel = NA,
        ..exposures = NA,
        ..autoScreen = NA,
        ..ciLevel = NA,
        ..showForest = NA,
        ..showFit = NA)
)

obtlogisticResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "obtlogisticResults",
    inherit = jmvcore::Group,
    active = list(
        univarTable = function() private$.items[["univarTable"]],
        multivarTable = function() private$.items[["multivarTable"]],
        fitTable = function() private$.items[["fitTable"]],
        forestPlot = function() private$.items[["forestPlot"]],
        logisticNote = function() private$.items[["logisticNote"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Logistic Regression")
            self$add(jmvcore::Table$new(
                options=options,
                name="univarTable",
                title="Univariable Analysis (crude OR)",
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="level", 
                        `title`="Level", 
                        `type`="text"),
                    list(
                        `name`="or", 
                        `title`="Crude OR", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ci_low", 
                        `title`="CI Low", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ci_high", 
                        `title`="CI High", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="p_value", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="screened", 
                        `title`="In MV model", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="multivarTable",
                title="Multivariable Analysis (adjusted OR)",
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="or", 
                        `title`="Adj. OR", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ci_low", 
                        `title`="CI Low", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ci_high", 
                        `title`="CI High", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="p_value", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="fitTable",
                title="Model Fit Statistics",
                visible="(showFit)",
                columns=list(
                    list(
                        `name`="metric", 
                        `title`="Statistic", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="forestPlot",
                title="Adjusted OR Forest Plot",
                width=560,
                height=380,
                renderFun=".plotForest",
                visible="(showForest)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="logisticNote",
                title="Methods & References",
                visible="always"))}))

obtlogisticBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "obtlogisticBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "outbreakTools",
                name = "obtlogistic",
                version = c(1,0,0),
                options = options,
                results = obtlogisticResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Logistic Regression
#'
#' 
#' @param data .
#' @param outcomeVar .
#' @param caseLevel .
#' @param exposures .
#' @param autoScreen .
#' @param ciLevel .
#' @param showForest .
#' @param showFit .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$univarTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$multivarTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$fitTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$forestPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$logisticNote} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$univarTable$asDF}
#'
#' \code{as.data.frame(results$univarTable)}
#'
#' @export
obtlogistic <- function(
    data,
    outcomeVar,
    caseLevel = "1",
    exposures,
    autoScreen = TRUE,
    ciLevel = 0.95,
    showForest = TRUE,
    showFit = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("obtlogistic requires jmvcore to be installed (restart may be required)")

    if ( ! missing(outcomeVar)) outcomeVar <- jmvcore::resolveQuo(jmvcore::enquo(outcomeVar))
    if ( ! missing(exposures)) exposures <- jmvcore::resolveQuo(jmvcore::enquo(exposures))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(outcomeVar), outcomeVar, NULL),
            `if`( ! missing(exposures), exposures, NULL))


    options <- obtlogisticOptions$new(
        outcomeVar = outcomeVar,
        caseLevel = caseLevel,
        exposures = exposures,
        autoScreen = autoScreen,
        ciLevel = ciLevel,
        showForest = showForest,
        showFit = showFit)

    analysis <- obtlogisticClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

