
# This file is automatically generated, you probably don't want to edit this

obtstratifiedOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "obtstratifiedOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            exposureVar = NULL,
            exposedLevel = "1",
            outcomeVar = NULL,
            caseLevel = "1",
            stratVar = NULL,
            studyDesign = "cohort",
            ciLevel = 0.95, ...) {

            super$initialize(
                package="outbreakTools",
                name="obtstratified",
                requiresData=TRUE,
                ...)

            private$..exposureVar <- jmvcore::OptionVariable$new(
                "exposureVar",
                exposureVar,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor",
                    "id"))
            private$..exposedLevel <- jmvcore::OptionString$new(
                "exposedLevel",
                exposedLevel,
                default="1")
            private$..outcomeVar <- jmvcore::OptionVariable$new(
                "outcomeVar",
                outcomeVar,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor",
                    "id"))
            private$..caseLevel <- jmvcore::OptionString$new(
                "caseLevel",
                caseLevel,
                default="1")
            private$..stratVar <- jmvcore::OptionVariable$new(
                "stratVar",
                stratVar,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor",
                    "id"))
            private$..studyDesign <- jmvcore::OptionList$new(
                "studyDesign",
                studyDesign,
                options=list(
                    "cohort",
                    "casecontrol"),
                default="cohort")
            private$..ciLevel <- jmvcore::OptionNumber$new(
                "ciLevel",
                ciLevel,
                min=0.8,
                max=0.99,
                default=0.95)

            self$.addOption(private$..exposureVar)
            self$.addOption(private$..exposedLevel)
            self$.addOption(private$..outcomeVar)
            self$.addOption(private$..caseLevel)
            self$.addOption(private$..stratVar)
            self$.addOption(private$..studyDesign)
            self$.addOption(private$..ciLevel)
        }),
    active = list(
        exposureVar = function() private$..exposureVar$value,
        exposedLevel = function() private$..exposedLevel$value,
        outcomeVar = function() private$..outcomeVar$value,
        caseLevel = function() private$..caseLevel$value,
        stratVar = function() private$..stratVar$value,
        studyDesign = function() private$..studyDesign$value,
        ciLevel = function() private$..ciLevel$value),
    private = list(
        ..exposureVar = NA,
        ..exposedLevel = NA,
        ..outcomeVar = NA,
        ..caseLevel = NA,
        ..stratVar = NA,
        ..studyDesign = NA,
        ..ciLevel = NA)
)

obtstratifiedResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "obtstratifiedResults",
    inherit = jmvcore::Group,
    active = list(
        crudeTable = function() private$.items[["crudeTable"]],
        strataTable = function() private$.items[["strataTable"]],
        mhTable = function() private$.items[["mhTable"]],
        bdTable = function() private$.items[["bdTable"]],
        mhNote = function() private$.items[["mhNote"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Stratified Analysis (Mantel-Haenszel)")
            self$add(jmvcore::Table$new(
                options=options,
                name="crudeTable",
                title="Crude (Unadjusted) Estimate",
                columns=list(
                    list(
                        `name`="measure", 
                        `title`="Measure", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="Estimate", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ci_low", 
                        `title`="CI Low", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ci_high", 
                        `title`="CI High", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="p_value", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="strataTable",
                title="Stratum-Specific Estimates",
                columns=list(
                    list(
                        `name`="stratum", 
                        `title`="Stratum", 
                        `type`="text"),
                    list(
                        `name`="a", 
                        `title`="a", 
                        `type`="integer"),
                    list(
                        `name`="b", 
                        `title`="b", 
                        `type`="integer"),
                    list(
                        `name`="c", 
                        `title`="c", 
                        `type`="integer"),
                    list(
                        `name`="d", 
                        `title`="d", 
                        `type`="integer"),
                    list(
                        `name`="estimate", 
                        `title`="RR / OR", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ci_low", 
                        `title`="CI Low", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ci_high", 
                        `title`="CI High", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="mhTable",
                title="Mantel-Haenszel Adjusted Estimate",
                columns=list(
                    list(
                        `name`="measure", 
                        `title`="Measure", 
                        `type`="text"),
                    list(
                        `name`="crude", 
                        `title`="Crude", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="adjusted", 
                        `title`="MH Adjusted", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ci_low", 
                        `title`="CI Low", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ci_high", 
                        `title`="CI High", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="p_value", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="bdTable",
                title="Breslow-Day Test (Effect Modification)",
                columns=list(
                    list(
                        `name`="test", 
                        `title`="Test", 
                        `type`="text"),
                    list(
                        `name`="stat", 
                        `title`="Chi-sq", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="interp", 
                        `title`="Interpretation", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="mhNote",
                title="Interpretation & References",
                visible="always"))}))

obtstratifiedBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "obtstratifiedBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "outbreakTools",
                name = "obtstratified",
                version = c(1,0,0),
                options = options,
                results = obtstratifiedResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Stratified Analysis (Mantel-Haenszel)
#'
#' 
#' @param data .
#' @param exposureVar .
#' @param exposedLevel .
#' @param outcomeVar .
#' @param caseLevel .
#' @param stratVar .
#' @param studyDesign .
#' @param ciLevel .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$crudeTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$strataTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$mhTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$bdTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$mhNote} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$crudeTable$asDF}
#'
#' \code{as.data.frame(results$crudeTable)}
#'
#' @export
obtstratified <- function(
    data,
    exposureVar,
    exposedLevel = "1",
    outcomeVar,
    caseLevel = "1",
    stratVar,
    studyDesign = "cohort",
    ciLevel = 0.95) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("obtstratified requires jmvcore to be installed (restart may be required)")

    if ( ! missing(exposureVar)) exposureVar <- jmvcore::resolveQuo(jmvcore::enquo(exposureVar))
    if ( ! missing(outcomeVar)) outcomeVar <- jmvcore::resolveQuo(jmvcore::enquo(outcomeVar))
    if ( ! missing(stratVar)) stratVar <- jmvcore::resolveQuo(jmvcore::enquo(stratVar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(exposureVar), exposureVar, NULL),
            `if`( ! missing(outcomeVar), outcomeVar, NULL),
            `if`( ! missing(stratVar), stratVar, NULL))


    options <- obtstratifiedOptions$new(
        exposureVar = exposureVar,
        exposedLevel = exposedLevel,
        outcomeVar = outcomeVar,
        caseLevel = caseLevel,
        stratVar = stratVar,
        studyDesign = studyDesign,
        ciLevel = ciLevel)

    analysis <- obtstratifiedClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

