
# This file is automatically generated, you probably don't want to edit this

obtsamplesizeOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "obtsamplesizeOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            studyType = "cohort",
            p0 = 20,
            effect = 2,
            alpha = "0.05",
            power = "0.80",
            ratio = 1, ...) {

            super$initialize(
                package="outbreakTools",
                name="obtsamplesize",
                requiresData=FALSE,
                ...)

            private$..studyType <- jmvcore::OptionList$new(
                "studyType",
                studyType,
                options=list(
                    "cohort",
                    "casecontrol",
                    "crosssectional"),
                default="cohort")
            private$..p0 <- jmvcore::OptionNumber$new(
                "p0",
                p0,
                min=0.1,
                max=99.9,
                default=20)
            private$..effect <- jmvcore::OptionNumber$new(
                "effect",
                effect,
                min=0.01,
                max=20,
                default=2)
            private$..alpha <- jmvcore::OptionList$new(
                "alpha",
                alpha,
                options=list(
                    "0.05",
                    "0.01",
                    "0.10"),
                default="0.05")
            private$..power <- jmvcore::OptionList$new(
                "power",
                power,
                options=list(
                    "0.80",
                    "0.90",
                    "0.95"),
                default="0.80")
            private$..ratio <- jmvcore::OptionNumber$new(
                "ratio",
                ratio,
                min=1,
                max=5,
                default=1)

            self$.addOption(private$..studyType)
            self$.addOption(private$..p0)
            self$.addOption(private$..effect)
            self$.addOption(private$..alpha)
            self$.addOption(private$..power)
            self$.addOption(private$..ratio)
        }),
    active = list(
        studyType = function() private$..studyType$value,
        p0 = function() private$..p0$value,
        effect = function() private$..effect$value,
        alpha = function() private$..alpha$value,
        power = function() private$..power$value,
        ratio = function() private$..ratio$value),
    private = list(
        ..studyType = NA,
        ..p0 = NA,
        ..effect = NA,
        ..alpha = NA,
        ..power = NA,
        ..ratio = NA)
)

obtsamplesizeResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "obtsamplesizeResults",
    inherit = jmvcore::Group,
    active = list(
        ssTable = function() private$.items[["ssTable"]],
        powerTable = function() private$.items[["powerTable"]],
        powerPlot = function() private$.items[["powerPlot"]],
        ssNote = function() private$.items[["ssNote"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Sample Size Calculator")
            self$add(jmvcore::Table$new(
                options=options,
                name="ssTable",
                title="Sample Size Requirements",
                columns=list(
                    list(
                        `name`="parameter", 
                        `title`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="powerTable",
                title="Power Curve",
                columns=list(
                    list(
                        `name`="effect", 
                        `title`="Effect Size (RR/OR)", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="n80", 
                        `title`="N (80% power)", 
                        `type`="integer"),
                    list(
                        `name`="n90", 
                        `title`="N (90% power)", 
                        `type`="integer"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="powerPlot",
                title="Power Curve Plot",
                width=500,
                height=340,
                renderFun=".plotPower"))
            self$add(jmvcore::Html$new(
                options=options,
                name="ssNote",
                title="Methods & References",
                visible="always"))}))

obtsamplesizeBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "obtsamplesizeBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "outbreakTools",
                name = "obtsamplesize",
                version = c(1,0,0),
                options = options,
                results = obtsamplesizeResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Sample Size Calculator
#'
#' 
#' @param data .
#' @param studyType .
#' @param p0 .
#' @param effect .
#' @param alpha .
#' @param power .
#' @param ratio .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$ssTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$powerTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$powerPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$ssNote} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$ssTable$asDF}
#'
#' \code{as.data.frame(results$ssTable)}
#'
#' @export
obtsamplesize <- function(
    data,
    studyType = "cohort",
    p0 = 20,
    effect = 2,
    alpha = "0.05",
    power = "0.80",
    ratio = 1) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("obtsamplesize requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- obtsamplesizeOptions$new(
        studyType = studyType,
        p0 = p0,
        effect = effect,
        alpha = alpha,
        power = power,
        ratio = ratio)

    analysis <- obtsamplesizeClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

